urls.py
#!/usr/bin/env python
# encoding: utf-8
"""
urls.py

Created by Eric Williams on 2007-02-27.
"""

from django.conf.urls.defaults import *
from django.contrib.sitemaps import GenericSitemap

from feeds import *
from models import Post
from views.sitemap import BlogSitemap

feeds = {
    'blogs': Posts,
    #'podcasts': Podcasts,
}

sitemaps = {
    'blog':BlogSitemap()
}
info_dict = {
    'queryset':Post.objects.all().filter(status='publish'),
    'date_field':'pub_date'
}

urlpatterns = patterns(  '',
    # (r'^gallery/$', 'blog.xmlrpc_views.call_xmlrpc', {'module':'gallery.galleryAPI'}),
    (r'^xmlrpc/*','xblog.views.xmlrpc_views.call_xmlrpc', {'module':'xblog.metaWeblog'}),
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
    (r'^.*/(?P<slug>[-\w]+)/edit/$',   'xblog.views.edit.edit_post'),
    (r'^.*/(?P<slug>[-\w]+)/trackback/$', 'xblog.ping_modes.process_trackback'),
    ('^$', 'xblog.views.blog.blog_overview'),
    # ('^archive/', include('blog.archive_urls')),
    )
urlpatterns += patterns(  'django.views.generic.date_based',
    (r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[-\w]+)/$',   'object_detail', dict(info_dict, slug_field='slug')),
    (r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$',                    'archive_day',   dict(info_dict,month_format="%b")),
    (r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$',                                     'archive_month', info_dict),
    (r'^(?P<year>\d{4})/$',                                                         'archive_year',  dict(info_dict, make_object_list=True)),
    (r'^archives/$',                                                               'archive_index', dict(info_dict)),
    # (r'^tag/(?P<tag>.*)/',                                                            'blog.views.tag_overview'),
)

urlpatterns += patterns(  'django.contrib.sitemaps.views',
    (r'^sitemap.xml$',      'index', {'sitemaps': sitemaps}),
    (r'^sitemap-blog.xml$', 'sitemap', {'sitemaps': sitemaps}),
)

models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User 
from django.core.mail import mail_managers, send_mail
from django.utils.text import truncate_html_words
from django.conf import settings
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager
from external import fuzzyclock
import datetime
import time
import os
import string


from mimetypes import guess_type
from external.markdown import Markdown
from external.smartypants import smartyPants
from external.postutils import SlugifyUniquely
# from external.BeautifulSoup import BeautifulSoup
import BeautifulSoup

STATUS_CHOICES=(('draft','Draft'),('publish','Published'),('private','Private'))
# text filters
FILTER_CHOICES=(
    ('markdown','Markdown'),
    ('html','HTML'),
    ('convert linebreaks','Convert linebreaks')
)

filters={}
def get_markdown(data):
    m = Markdown(data, 
                     extensions=['footnotes'],
                     # extension_configs= {'footnotes' : ('PLACE_MARKER','~~~~~~~~')},
                     encoding='utf8',
                     safe_mode = False
                     )
    res = m.toString()
    res = smartyPants(res, "1qb")
    return res
    
filters['markdown']=get_markdown

def get_html(data):
    # just return it.
    # maybe tidy it up or something...
    data = smartyPants(data, "1qb")
    return data

filters['html']=get_html

def convert_linebreaks(data):
    data = data.replace("\n", "<br />")
    return smartyPants(data,"1qb")

filters['convert linebreaks']=convert_linebreaks
filters['__default__']=convert_linebreaks

def xmlify(data):
    return data
    replaced=False
    for let in data:
        # fix non-unicodies.
        if ord(let) > 127:
            replaced=True
            print "Replacing %s -> &%d;" % (let,ord(let) )
            data = data.replace(let,"&#%d;" % ord(let))

    return data

class LinkCategory(models.Model):
    """Categories for  the blogroll"""
    title = models.CharField(blank=True, max_length=255)
    description = models.TextField(blank=True)
    visible = models.BooleanField(default=True)
    blog = models.ForeignKey('Blog')
    display_order = models.IntegerField(blank=True, null=True)
    
    # Admin moved to admin.py
    #class Admin:
    #    list_display = ('title',)
    #    search_fields = ('title',)

    def __str__(self):
        return str(self.title)
    __repr__=__str__


class Link(models.Model):
    """Blogroll Struct"""
    url = models.URLField(blank=True, verify_exists=True)
    link_name = models.CharField(blank=True, max_length=255)
    link_image = models.ImageField(upload_to="blog_uploads/links/", height_field='link_image_height', width_field='link_image_width',blank=True)
    link_image_height = models.IntegerField(blank=True, null=True)
    link_image_width = models.IntegerField(blank=True, null=True)
    
    description = models.TextField(blank=True)
    visible = models.BooleanField(default=True)
    blog = models.ForeignKey('Blog')
    rss = models.URLField(blank=True, verify_exists=True)
    
    category = models.ForeignKey('LinkCategory')
    
    def __str__(self):
        return "%s (%s)" % (self.link_name, self.url)
    
    __repr__=__str__

class Pingback(models.Model):
    """ Replies are either pingbacks """
    
    author_name = models.CharField(blank=True, max_length=100)
    author_email = models.EmailField(blank=True)
    post = models.ForeignKey('Post')
    title = models.CharField(blank=True, max_length=255)
    body = models.TextField(blank=True)
    is_public = models.BooleanField(default=False)
    
    source_url = models.URLField(blank=True, verify_exists=True)
    target_url = models.URLField(blank=True, verify_exists=False)
    pub_date = models.DateTimeField(blank=True, default=datetime.datetime.now())
    mod_date = models.DateTimeField(blank=True, default=datetime.datetime.now())
    
    def __str__(self):
        return "Reply %s -> %s" % (self.source_url,self.target_url)

    def __repr__(self):
        return "%s (%s - %s)" % (self.title, self.source_url, self.target_url)

    def save(self):
        super(self.__class__, self).save()
        mail_subject = "New Pingback from %s" % self.title.strip()
        mail_body = """        
        
Source URL: %s
Target URL: %s
      Time: %s
            """ % (self.source_url, self.target_url, self.pub_date)
            
        print mail_subject
        print mail_body
        # mail_managers(mail_subject, mail_body, fail_silently=False)
        send_mail(mail_subject, mail_body, "eric@xoffender.de", [self.post.author.email])
        
class Tag(models.Model):
    """(Tag description)"""
    title = models.CharField(blank=True, max_length=100)
    def __str__(self):
        # return "%s (%s - %s)" % (self.title, self.source_url, self.target_url)
        return self.title


class Author(models.Model):
    """User guy"""
    fullname = models.CharField(blank=True, max_length=100)
    url = models.URLField(blank=True, verify_exists=True)
    avatar = models.ImageField(blank=True, upload_to="users/avatars/", height_field='avatar_height', width_field='avatar_width')
    user = models.ForeignKey(User, unique=True)
    about = models.TextField(blank=True)
    avatar_height = models.IntegerField(blank=True, null=True)
    avatar_width = models.IntegerField(blank=True, null=True)
    # moved to admin.py
    #class Admin:
    #    # list_display = ('',)
    #    # search_fields = ('',)
    #    pass

    def __str__(self):
        return "%s (%s)" % (self.fullname,self.user.username)

class Category(models.Model):
    """Categories for Blog entries"""
    title = models.CharField(blank=True, max_length=100)
    description = models.CharField(blank=True, max_length=100)
    blog = models.ForeignKey("Blog")

    def __str__(self):
        return self.title


class Post(models.Model):
    """A Blog Entry, natch"""
    # metadata
    pub_date = models.DateTimeField(blank=True, default=datetime.datetime.now())
    update_date = models.DateTimeField(blank=True, auto_now=True) 
    create_date = models.DateTimeField(blank=True, auto_now_add=True)
    enable_comments = models.BooleanField(default=True)
    # post content 
    title = models.CharField(blank=False, max_length=255)
    slug = models.SlugField(max_length=100)
    body = models.TextField(blank=True)
    summary = models.TextField(blank=True)
    categories = models.ManyToManyField(Category)
    primary_category_name = models.ForeignKey(Category, related_name='primary_category_set', blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True, null=True)
    blog = models.ForeignKey('Blog')
    author = models.ForeignKey(User)
    status = models.CharField(blank=True, null=True, max_length=32, choices=STATUS_CHOICES, default="Draft")
    # filter to display when "get_formatted_body" is called.
    text_filter = models.CharField(blank=True, max_length=100, choices=FILTER_CHOICES, default='__default__')

    def __str__(self):
        return self.title
        
    def comment_period_open(self):
        """ determines if a post is too old..."""
        # uncomment rest of line to set limit at 30 days.
        # Sometimes I get hits on older entries, so I'll leave this one for now.
        return self.enable_comments # and datetime.datetime.today() - datetime.timedelta(30) <= self.pub_date
        
    
    def prepopulate(self):
        if not self.slug or self.slug=='':
            self.slug = SlugifyUniquely(self.title, self.__class__)
            
        if not self.summary or self.summary == '':
            # do an auto-summarize here.
            # now what could that be?
            pass

    def handle_technorati_tags(self):
        # takes the post, and returns the technorati links in them...
        # from ecto:
        start_tag = "<!-- technorati tags start -->"
        end_tag = "<!-- technorati tags end -->"
        text = self.body
        start_idx = text.find(start_tag) + len(start_tag)
        end_idx = text.find(end_tag)
        if start_idx==-1 or end_idx ==-1:
            return
        #print "Got target text: starts at", start_idx
        #print "Ends at", end_idx
        #print "Got:", text[start_idx:end_idx]
        soup = BeautifulSoup(text)
        tags = []
        for a in soup.findAll('a'):
            if "http://www.technorati.com/tag/" in a.get('href'):
                # seems to be taggy
                tags.append(a.string)
                
        print tags
        taglist = []
        for tag in tags:
            # try to find the tag
            try:
                t = Tag.objects.get(title__iexact=tag)
                print "Got '%s'" % t
            except:
                # not found, create tag
                print "Creating '%s'" % tag
                t = Tag(title = tag)
                t.save()

            taglist.append(t)
        
        self.tags = taglist

            
    def save(self):
        # convert this crapola to unicode
        # self.body = self.body.decode('utf-8')
        # print self.body
        #if not self.id:
        #    # replace self.name with your prepopulate_from field
        #    self.body = xmlify(self.body)
        #    self.title = xmlify(self.title)
            
        if not self.slug or self.slug=='':
            self.slug = SlugifyUniquely(self.title, self.__class__)
            
        # regen summary...
        
        self.summary=truncate_html_words(filters.get(self.text_filter, convert_linebreaks)(self.body), 50)
        
        # save to create my ID for the manytomany thing
        super(self.__class__, self).save()
        # self.handle_technorati_tags()
        # save again :-/
        # super(self.__class__, self).save()
        # check the outgoing pings...
        
    def get_archive_url(self):
        # returns the path in archive
        archive_url = settings.SITE_URL + "blog/archive/"

templates/xblog/blog_base.html
{% comment %}
{% extends "base_site.html" %}
{% endcomment %}
{% block extrahead %}
{% load  blog_tags %}
{% comment %}
{% load thumbnail %}
{% endcomment %}
<meta name="description" content="{{blog.description}}" />
<link rel="alternate" href="http://feeds.feedburner.com/youbitch/qGWn" type="application/rss+xml" title="RSS 2.0" />
<link rel="EditURI" href="{{ site_url }}blog/xmlrpc/" type="application/rsd+xml" title="RSD" />
<link rel="archives" href="{{  site_url }}blog/archive/" title="Archives" charset="utf-8" />
<link rel="pingback" href="{{ site_url }}blog/xmlrpc/" />
{% endblock %}
{% block pagetitle %}blog{% endblock %}
{% block pagestyle %}blog{% endblock %}
{% block leftnav %}{% endblock %}
<!-- main content -->
{% block maincontent %}

Main content goes here.

{% endblock %}
<!-- /main content -->

{% block rightnav %}
{% get_blogroll %}
<div id="blogroll">
	<h2>Latest Comments</h2>
	{% for cat in blogroll_categories %}
	<h2>{{ cat.title }}</h2>
	<ul>{% for link in cat.link_set.all|dictsort:"link_name" %}
	   <li class="blogroll"><a href="{{link.url}}">{{ link.link_name }}</a></li>
        {% endfor %}
        </ul>
{% endfor %}
	<p class="blogrollheader">Archives</p>
	{% get_blog_months %}
	{% for month in blog_months %}
	{% ifchanged %}{% if not forloop.first %}<br />{% endif %}<span class="blogrollheader"><a href="/blog/{{month.year}}">{{month|date:"Y"|lower}}</a></span><br />{% endifchanged %}
		<a href="/blog/{{ month|date:"Y/M"|lower }}/" title="{{ month|date:"M Y" }}">{{ month|date:"M" }}</a>
		{% ifequal month.month 6  %}<br />{% endifequal %}{% endfor %}
	</div><!-- /blogroll -->
{% endblock %}

templates/xblog/edit_post.html
{% extends "xblog/blog_base.html" %}

{% block maincontent %}
<form action="" method="post" accept-charset="utf-8">
	

	<p><input type="submit" value="Continue &rarr;"></p>


<table border="0" cellspacing="5" cellpadding="5">

{{ form.as_table }}	
</table>
</form>

{% endblock %}

templates/xblog/overview.html
{% extends "xblog/blog_base.html" %}
{% load markup %}
{% block extratitle %}{{pagetitle}}{% endblock %}
{% block navigation %}
&nbsp;&rsaquo;<a href="/blog/">Blog </a>
{% endblock %}
{% block maincontent %}
	<!-- begin main blog overview -->
	{% for post in latest_posts %}
	{% ifchanged %}<h2>{{ post.pub_date|date:"F d,Y"}}</h2>{% endifchanged %}
	<!-- a post -->
	<div id="post-{{ post.id }}" class="item entry">
		<div class="itemhead">
			<h3><a href="{{ post.get_absolute_url }}" title="{{ post.title }}">{{ post.title|safe }}</a></h3>
			<small class="metadata">
				<span class="chronodata">Posted by <span class="vcard author">{{ post.author.get_profile.fullname }}</span> 
				in 
				<span class="entry-category">{{ post.categories.all|join:","}}</span> at {{ post.pub_date|date:"f A" }}<br />
				<a class="commentslink" href="{{ post.get_absolute_url}}#comments" title="Comments on {{ post.title }}">{{ comment_count  }} Comments</a>  
				<a class="pingbacklink" href="{{ post.get_absolute_url }}#pingbacks" title="Pingbacks on {{ post.title }}">{{ post.get_pingback_count }} Pings</a></span>
			</small>	
		</div><!-- /itemhead -->
		<div class="entrycontent">
			{{ post.get_formatted_body|safe }}
		</div><!-- /entrycontent -->
	</div><!-- /a post -->
	{% endfor %}
	<!-- end main blog overview -->
{% endblock %}

templates/xblog/post_archive.html
{% extends "xblog/blog_base.html" %}
{% load markup %}
{% block extratitle %}
Blog Archives
{% endblock %}
{% block navigation %}&nbsp;&rsaquo;<a href="/blog">Blog</a>&nbsp;&rsaquo;<a href="/blog/archive/">Archives</a>{% block yearnav %}{% endblock %}{% block monthnav %}{% endblock %}{% block daynav %}{% endblock %}{% block objectnav %}{% endblock %}
	{% endblock %}
{% block maincontent %}
	<div id="content">
	{% for post in latest %}
	{% ifchanged %}
		<h2><a href="{{ post.get_year_archive_url}}">{{ post.pub_date|date:"Y" }}</h2>
	{% endifchanged %}
	{% ifchanged %}
	<!-- links for day -->
	<h3><a href="{{post.get_month_archive_url}}/">{{ post.pub_date|date:"F "}}</h3>{% endifchanged %}
	<p><a href="{{ post.get_absolute_url }}">{{post.title}}</a></p>
	<p class="postmeta"> Posted by {{ post.author.fullname }} at {{ post.pub_date|date:"P" }}  on {{ post.pub_date|date:"F j"}}</p>
	{% endfor %}
	</div>
{% endblock %}

templates/xblog/post_archive_day.html
{% extends "xblog/post_archive_month.html" %}
{% block yearnav %}&nbsp;&rsaquo;<a href="../../">{{day|date:"Y"}}</a>{% endblock %}{% block monthnav %}&nbsp;&rsaquo;<a href="..">{{day|date:"F"}}</a>{% endblock %}&nbsp;&rsaquo;{% block daynav %}&nbsp;&rsaquo;{{day|date:"d"}}{% endblock %}

templates/xblog/post_archive_month.html
{% extends "xblog/post_archive_year.html" %}
{% block pagetitle %}{{ thisblog.title }} Archive for {{month|date:"F Y" }}{% endblock %}
{% block yearnav %}&nbsp;&rsaquo;<a href="../">{{month|date:"Y"}}</a>{% endblock %}{% block monthnav %}&nbsp;&rsaquo;{{month|date:"F"}}{% endblock %}
{% block maincontent %}
{% comment %}
{% load comments %}
{% endcomment %}
{% for post in object_list %}
{% ifchanged %}<p>Back to <a href="/blog/">Recent Post</a></p>{% endifchanged %}
{% ifchanged %}<p>Back to <a href="{{ post.get_year_archive_url }}">{{ post.pub_date|date:"Y"}}</a></p>{% endifchanged %}
{% ifchanged %}<h2><a href="{{ post.get_month_archive_url }}">{{ post.pub_date|date:"F"}}</a></h2>{% endifchanged %}

{% comment %}
{% get_free_comment_count for xblog.post post.id as comment_count %}
{% endcomment %}
<!-- a post -->
<div id="post-{{ post.id }}" class="item entry">
	<div class="itemhead">
		<h3><a href="{{ post.get_absolute_url }}" title="{{ post.title }}">{{ post.title}}</a></h3>
		<small class="metadata">
			<span class="chronodata">Posted by <span class="vcard author">{{ post.author.get_profile.fullname }} on {{ post.pub_date|date:"jS o\f F, Y" }}</span> 
			in 
			<span class="entry-category">{{ post.categories.all|join:","}}</span><br />
			<a class="commentslink" href="{{ post.get_absolute_url}}#comments" title="Comments on {{ post.title }}">{{ comment_count  }} Comments</a>  <a class="pingbacklink" href="{{ post.get_absolute_url }}#pingbacks" title="Pingbacks on {{ post.title }}">{{ post.get_pingback_count }} Pings</a>
		</small>	
	</div><!-- /itemhead -->
</div>
<!-- /a post -->

{% endfor %}
{% endblock %}

templates/xblog/post_archive_year.html
{% extends "xblog/blog_base.html" %}
{% block pagetitle %}{{ thisblog.title }} Yearly Archive for {{ year}}{% endblock %}
{% block maincontent %}

	{% for post in object_list %}
	{% ifchanged %}<h2><a href="{{ post.get_month_archive_url }}">{{ post.pub_date|date:"F Y"}}</a></h2>{% endifchanged %}
	{% comment %}
    {% get_free_comment_count for xblog.post post.id as comment_count %}
    {% endcomment %}
	<!-- a post -->
	<div id="post-{{ post.id }}" class="item entry">
		<div class="itemhead">
			<h3><a href="{{ post.get_absolute_url }}" title="{{ post.title }}">{{ post.title}}</a></h3>
			<small class="metadata">
				<span class="chronodata">Posted by <span class="vcard author">{{ post.author.get_profile.fullname }}</span> 
				in 
				<span class="entry-category">{{ post.categories.all|join:","}}</span> at {{ post.pub_date|date:"P" }} on {{ post.pub_date|date:"F j" }}<br />
				<a class="commentslink" href="{{ post.get_absolute_url}}#comments" title="Comments on {{ post.title }}">{{ comment_count  }} Comments</a>  <a class="pingbacklink" href="{{ post.get_absolute_url }}#pingbacks" title="Pingbacks on {{ post.title }}">{{ post.get_pingback_count }} Pings</a>
			</small>	
		</div><!-- /itemhead -->
	</div>
	<!-- /a post -->

	{% endfor %}
{% endblock %}

templates/xblog/post_detail.html
{% extends "xblog/post_archive.html" %}
{% load markup %}
{% block extratitle %}{{ object.title }}{% endblock %}
{% block yearnav %}&nbsp;&rsaquo;<a href="../../../">{{object.pub_date|date:"Y"}}</a>{% endblock %}{% block monthnav %}&nbsp;&rsaquo;<a href="../../">{{object.pub_date|date:"F"}}</a>{% endblock %}{% block daynav %}&nbsp;&rsaquo;<a href="../">{{object.pub_date|date:"d"}}</a>{% endblock %}
{% block extrarightnav %}
	
{% endblock %}	
{% block maincontent %}
<!-- a post -->
<div id="post-{{ object.id }}" class="item entry">
	<div class="itemhead">
		<h3><a href="{{ object.get_absolute_url }}" title="{{ object.title }}">
		{{ object.title|safe}}
		</a></h3>
		<small class="metadata">
			<span class="chronodata">Posted by <span class="vcard author">{{ object.author.get_profile.fullname }}</span> 
			in 
			<span class="entry-category">{{ object.categories.all|join:","}}</span> at {{ object.pub_date|date:"P"}} on {{ object.pub_date|date:"N dS, Y"}}<br />
			<a class="commentslink" href="#comments" title="Comments on {{ object.title }}">{{ comment_count  }} Comments</a>  <a class="pingbacklink" href="#pingbacks" title="Pingbacks on {{ object.title }}">{{ object.get_pingback_count }} Pings</a></span>
		</small>	
	</div><!-- /itemhead -->
	<div class="entrycontent">
		{{ object.get_full_body|safe }}
	</div><!-- entrycontent -->
</div>
<!-- /a post -->
	<!--
	<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
				xmlns:dc="http://purl.org/dc/elements/1.1/"
				xmlns:trackback="http://madskills.com/public/xml/rss/module/trackback/">
			<rdf:Description rdf:about="{{ object.get_absolute_uri}}"
	    		dc:identifier="{{ object.get_absolute_uri }}"
			dc:title="{{ object.title }}"
			trackback:ping="{{ object.get_absolute_uri }}trackback/" />
	</rdf:RDF> -->
	<!-- begin comments -->

{% comment %}
	{% get_free_comment_count for xblog.post object.id as comment_count %}
	{% get_free_comment_list for xblog.post object.id as comment_list %}
{% endcomment %}

	{% for pb in object.pingback_set.all %}
	{% ifchanged %}<h3>Pingbacks</h3>
		<a id="pingbacks"></a>{% endifchanged %}
		<div class="comment">
			<span class="comnum"><a href="{{pb.source_url}}">{{ pb.title }}</a>&rarr;<a href="{{ pb.target_url }}"></a></span>
		</div><!-- /comment -->
	{% endfor %}
	<a id="comments"></a>
	<h3>Comments</h3>
	{% for comment in comment_list %}
		<div class="comment {% cycle odd,even %}" id="c{{ comment.id }}">
			<span class="comnum"><a id="c{{ comment.id }}" href="#c{{ comment.id }}"></a></span>
			<h3><a href="{{comment.person_url}}">{{ comment.person_name }}</a></h3>
		    <small class="postmeta"><a class="commentslink" href="{{ comment.person_url }}">{{ comment.submit_date|date:"F j, Y" }} at {{ comment.submit_date|date:"P" }}:</a></small>
			{{ comment.comment|urlizetrunc:40|markdown:"footnotes" }}
		</div><!-- /comment-{{ comment.id }} -->
	{% endfor %}
	<div id="commentform">
{% comment %}
	{% if object.comment_period_open %}

		{% free_comment_form for xblog.post object.id %}
	{% else %}
		<p>Comments for "{{ object.title }}" are closed.</p>
	{% endif %}
    
{% endcomment %}
	</div><!-- /commentform -->
{% endblock %}